manifest: track prebuilts/kernel-build-tools repo
Fixes following build error:
  scripts/extract-cert.c:21:10: fatal error: 'openssl/bio.h' file not found

- Required for GKI Kernels

Change-Id: I0c88ae8c4fc84f604ae4fc4ac6f949a1cfc871ed